import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

working_directory = "/home/catniped/"

[shell]
program = "zsh"

[font]
normal = { family = "EnvyCodeR Nerd Font", style = "Regular" }
bold = { family = "EnvyCodeR Nerd Font", style = "Bold" }
italic = { family = "EnvyCodeR Nerd Font", style = "Italic" }

[window]
decorations = "Full"
title = "alacritter real"
opacity = 0.85
